config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    get "advertisment", to: "advertisments#index", as: :admin_advertisments
    get "advertisments/configuration", to: "advertisments_configurations#configure", as: :advertisments_configurations
    patch "advertisments/configuration", to: "advertisments_configurations#configure", as: :advertisments_configurations_update
    resources :advertisments
  end
end

app/models/concerns/advertisable.rb
module Concerns::Advertisable
  extend ActiveSupport::Concern
  included do
    has_many :spree_advertisment, :as => :advrt_rf, class_name: 'Spree::Advertisment'
  end
end

app/models/concerns/advertisable_information.rb
module Concerns::AdvertisableInformation
  extend ActiveSupport::Concern

  included do
    def get_advertise code
      return Spree::Advertisment.None if code.nil?
      return spree_advertisment.where(code: code, active: true)
    end
  end
end

app/models/concerns/configuration_gem.rb
module Concerns::ConfigurationGem
    extend ActiveSupport::Concern

    included do
        attr_reader :preferences_obj
        before_save :update_preferences

        def init_configuration
            if self.preferences.blank?
                self.preferences = "{'enable': true}"
            end
            @preferences_obj = eval(self.preferences)
            self
        end

        def get_preferences_obj
            @preferences_obj ||= init_configuration.preferences_obj
            @preferences_obj
        end

        def set_preferences_obj preferences
            @preferences_obj = preferences
            self
        end

        def method_missing name, *args, &block
            name_attribute = name.to_s
            return super(name, *args, &block) if !name_attribute.include?("is_") || !name_attribute.include?("_like_")
            name_attribute = name_attribute.gsub("?", "").gsub("is_", "")
            data = name_attribute.split("_like_")
            get_preferences_obj[data[0].to_sym] == (data[1].is_a?(String) ? eval(data[1]) : data[1])
        end

        def set_opt opt, value
            get_preferences_obj()[opt]= value
            self
        end

        def update_preferences
            unless @preferences_obj.nil?
                self.preferences = @preferences_obj.to_s
            end
        end

        def get_preference(key)
            return eval(get_preferences_obj[key].to_s) if get_preferences_obj.include?(key)
            return nil
        end

        class << self
            def get_configuration
                config = first_or_initialize
                config.init_configuration
            end
        end
    end
end

app/models/spree/advertisment.rb
class Spree::Advertisment < ApplicationRecord
  belongs_to :advrt_rf, polymorphic: true
  validates_presence_of :code, :content
  TYPES_ADVERTISMENT = ["image?", "video?", "text?"]

  def method_helper_is_knowledge(method_name)
    TYPES_ADVERTISMENT.each do |type|
      if method_name.include?(type)
        return true
      end
    end
    return false
  end

  def method_missing(m, *args, &block)
    return super(m, *args, &block) unless method_helper_is_knowledge(m.to_s)
    type = m.to_s.split("_")[-1]
    return type_advertisement == type.split("?")[0]
  end
end

app/models/spree/advertisments_configuration.rb
class Spree::AdvertismentsConfiguration < ApplicationRecord
    include Concerns::ConfigurationGem
    
    def self.enable
        get_configuration.set_opt("enable", true).save
    end

    def self.disable
        get_configuration.set_opt("enable", false).save
    end

    def self.is_enable?
        get_configuration.is_enable_like_true?
    end

    def self.is_disable?
        get_configuration.is_enable_like_false?
    end

    def self.set_preferences preferences
        config = get_configuration.set_preferences_obj preferences
        config.save
    end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  include Concerns::Advertisable
  include Concerns::AdvertisableInformation
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  include Concerns::Advertisable
  include Concerns::AdvertisableInformation
end

app/controllers/spree/admin/advertisment_controller.rb
class Spree::Admin::AdvertismentController < Spree::Admin::ResourceController
  before_action :collection, only: :index
  before_action :define_new_object, only: :new
  before_action :define_edit_object, only: :edit

  def index
    session[:return_to]
    respond_with(@collection)
  end

  def model_class
    @model_class ||= Spree::Advertisment
  end

  private
  def collection
    @collection = Spree::Advertisment.all
  end

  def load_index_data
    #@image = Spree::Image.find(params[:image_id])
  end

  def load_edit_data
  end

  def define_new_object
    @advertisment = Spree::Advertisment.new
  end

  def define_edit_object
    @advertisment = Spree::Advertisment.find(params[:id])
  end

  def checking
    binding.pry
  end

  def collection_url
    admin_advertisment_index_url
  end
end

app/controllers/spree/admin/advertisments_configurations_controller.rb
class Spree::Admin::AdvertismentsConfigurationsController < Spree::Admin::ResourceController
    
    def configure
        unless params[:advertisments_configuration].nil?
            update_configuration
        else
            @object = Spree::AdvertismentsConfiguration.get_configuration
        end
    end

    def update_configuration
        preferences_param = permitted_params[:preferences]
        if permitted_params[:preferences].is_a?(String)
            preferences_param = eval(permitted_params[:preferences])
        end
        if @model_class.set_preferences preferences_param
            return respond_to do |format|
                flash[:notice] = Spree.t(:advertisment_configuration_sucessfuly_updated)
                format.html {redirect_to admin_advertisments_configurations_url}
            end
        else
            flash[:notice] = Spree.t(:advertisment_configuration_error_updated)
            render "configure"
        end
        
    end

    def model_class
        @model_class ||= Spree::AdvertismentsConfiguration
    end

    
    private
    def permitted_params
       #params.require("advertisments_configuration").permit(:preferences=> [:enable])
       params.require("advertisments_configuration").permit(:preferences)
    end

end

app/controllers/spree/admin/advertisments_controller.rb
class Spree::Admin::AdvertismentsController < Spree::Admin::ResourceController
  before_action :collection, only: :index
  before_action :define_new_object, only: :new
  before_action :define_edit_object, only: :edit

  def index
    session[:return_to]
    respond_with(@collection)
  end

  def model_class
    @model_class ||= Spree::Advertisment
  end

  private
  def collection
    @collection = Spree::Advertisment.all
  end

  def load_index_data
    #@image = Spree::Image.find(params[:image_id])
  end

  def load_edit_data
  end

  def define_new_object
    @advertisment = Spree::Advertisment.new
  end

  def define_edit_object
    @advertisment = Spree::Advertisment.find(params[:id])
  end

  def collection_url
    admin_advertisments_url
  end
end

app/helpers/advertisment_logic_helper.rb
module AdvertismentLogicHelper

  def get_advertisment_by_code code
    return Spree::Advertisment.None if code.nil?
    return Spree::Advertisment.find_by_code_and_active(code, true)
  end

  def get_advertisment_content_by_code code
    advertisment = get_advertisment_by_code code
    return "" if advertisment.nil?
    return image_tag(advertisment.content) if advertisment.is_an_image?
    return content_tag("span", advertisment.content) if advertisment.is_a_text?
    return video_tag(advertisment.content) if advertisment.is_a_video?
    return ""
  end
end

app/views/spree/admin/advertisments/_form.html.erb
<div data-hook="admin_image_form_fields" class="row">
  <div class="col-xs-12 col-md-6">
    <div data-hook="code" class="form-group">
      <%= f.label :code, Spree.t(:code) %>
      <%= f.text_field :code %>
    </div>
    <div data-hook="type_advertisement" class="form-group">
      <%= f.label :type_advertisement, Spree.t(:type_advertisement) %>
      <%= f.text_field :type_advertisement %>
    </div>
    <div data-hook="advrt_rf_id" class="form-group">
      <%= f.label :advrt_rf_id, Spree.t(:advrt_rf_id) %>
      <%= f.text_field :advrt_rf_id %>
    </div>
  </div>
</div>

app/views/spree/admin/advertisments/_menu_options_advertisment.html.erb
<ul class="nav nav-sidebar">
  <li class="sidebar-menu-item"><a data-toggle="collapse" data-parent="#sidebar" href="#sidebar-configuration-advertisment"><span class="icon icon-wrench"></span><span class="text">Anuncios</span><span class="icon icon-chevron-left pull-right"></span></a>
    <ul data-hook="admin_configurations_sidebar_menu" class="collapse nav nav-pills nav-stacked" id="sidebar-configuration-advertisment">
      <%= tab Spree::Advertisment, url: admin_advertisments_configurations_path, icon: "file", label: "Configuración de la gema" %>
      <%= tab Spree::Advertisment, url: admin_admin_advertisments_path, icon: "file", label: "Anuncios" %>
      <%= tab Spree::Advertisment, url: new_admin_advertisment_path, icon: "file", label: "Crear nuevo anuncio" %>
    </ul>
  </li>
</ul>

app/views/spree/admin/advertisments/edit.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @object } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_advertisment) %>
<% end %>

<%= form_for [:admin, @object], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_image">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/advertisments/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:advertisment) %>
<% end %>

<table class="table" id="listing_advertisment">
  <thead>
    <tr>
      <th><%= Spree.t(:id) %></th>
      <th><%= Spree.t(:code) %></th>
      <th><%= Spree.t(:type) %></th>
      <th><%= Spree.t(:view_content) %></th>
      <th data-hook="admin_advertisment_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @collection.each do |advertisment| %>
      <tr data-hook="admin_advertisment_index_rows" id="<%= dom_id advertisment %>" class="<%= cycle('odd', 'even') %>">
        <td><%= advertisment.id %></td>
        <td><%= advertisment.code %></td>
        <td><%= advertisment.type_advertisement %></td>
        <td><span>Ver contenido</span></td>
        <td data-hook="admin_advertisment_index_row_actions" class="actions">
          <%= link_to_edit advertisment, no_text: true, class: 'edit' %>
          <%= link_to_delete advertisment, no_text: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/advertisments/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @object } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_advertisment) %>
<% end %>

<%= form_for [:admin, @object], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_image">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/advertisments_configurations/_form.html.erb
<div data-hook="admin_advertisments_configurations_form_fields" class="row">
  <div class="col-xs-12 col-md-6">
    <div data-hook="code" class="form-group">
      <%= f.label :enable, Spree.t(:enable) %>
      <%= f.check_box "preferences", {checked: (f.object.get_preference(:enable) ? "checked" : '') }, {enable: true}, {enable: false} %>
    </div>
  </div>
</div>

app/views/spree/admin/advertisments_configurations/configure.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:change_advertisment_configuration) %>
<% end %>

<%= form_for [:admin, @object], url: admin_advertisments_configurations_update_path, html: { multipart: true } do |f| %>
  <fieldset data-hook="change_advertisment_configuration">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
    </div>
  </fieldset>
<% end %>